### ISSUE TITLE
this cod make error in demo.py 

### ISSUE THREAD

**Issue by youngjaean** [va1shn9v/PromptIR#1]
https://github.com/va1shn9v/PromptIR/blob/main/demo.py#L77

what is mean parameter?  x_query and x_key.

**Comment by youngjaean** [comment]
If i run the code after modifying it, the result is strange. The model doesn't seem to work
this is before image
![blurring_cat](https://github.com/va1shn9v/PromptIR/
this is after image 
![blurring_cat](https://github.com/va1shn9v/PromptIR/assets/30186158/76568bd1-e2ea-4c7a-9567-eec591482249)
assets/30186158/167376c1-7bc0-471c-8cdc-04938eded532)

**Comment by va1shn9v** [comment]
Hello, Thanks for taking an interest in our work, the parameters mentioned above are remnants of old developmental code, they have been removed now.
The PromptIR model is trained on Dehazing, Deraining and Denoising tasks and the input image used seems to be blurry, hence the model wont be able to restore it.

**Comment by youngjaean** [comment]
oh! thx 4 u answer  this is my mistake.
I like this project and i have interest.
