### ISSUE TITLE
wanna ask how to place the denoising dataset (training stage)

### ISSUE THREAD

**Issue by Haochen-CUHK** [va1shn9v/PromptIR#11]
Hello, sorry to bother you in your busy schedule.

I have download the dataset for denoising training stage, but I don't know how to configure and place it and wanna ask for advice.

Thanks!

**Comment by va1shn9v** [comment]
Hello, Thanks a lot for taking an interest in our work. For the denoising training data you can extract the images from the zip files and directly place in the in the  Train/Denoise/ directory. The images from both the WED and BSD400 datasets can put together in the Train/Denoise/ directory.
