### ISSUE TITLE
The problem of dataset

### ISSUE THREAD

**Issue by blingsr** [va1shn9v/PromptIR#13]
Hi, I have a problem: the model reported that there is no such image, but I saw that there is such an image in the folder. What's the matter?

FileNotFoundError: [Errno 2] No such file or directory: 'home/chenz/Promptir/data/Train/Derain/rainy/rain-81.png'

**Comment by House-yuyu** [comment]
@blingsr, hi, make sure that in the corresponding rainTrain.txt, the filename is stored in the format '**rainy**/rain-xxx.png'

**Comment by zhousai-zs** [comment]
> @blingsr, hi, make sure that in the corresponding rainTrain.txt, the filename is stored in the format '**rainy**/rain-xxx.png'

我在Rain100L上使用官方提供的model.ckpt测得PSNR为37.44，这与paper report中相差甚大，能否解答一下？
