### ISSUE TITLE
Why the deraining performance of Restormer is not same as original paper?

### ISSUE THREAD

**Issue by Luciennnnnnn** [va1shn9v/PromptIR#16]
In the PromptIR paper, it is 36.74 dB and 38.99 dB in original paper, how this huge difference come from?

**Comment by jaroslaw1007** [comment]
Hi,

I think it is because the results in PromptIR paper are evaluated in all of RGB channels, on the other hand, the results in Restormer paper are computed by only using Y channel in YCbCr.

**Comment by chensming** [comment]
> In the PromptIR paper, it is 36.74 dB and 38.99 dB in original paper, how this huge difference come from?

They are trained on different datasets, restormer is trained on rain13k, while prompIR is trained on rain100L.
