### ISSUE TITLE
Cuda out of memory error?

### ISSUE THREAD

**Issue by zelenooki87** [va1shn9v/PromptIR#2]
Is there any chance to inference with tile option to avoid oom errors? tnx

**Comment by va1shn9v** [comment]
Hello, Thanks for taking an interest in our work, we will be adding tiling inference in the next few days

**Comment by heorhiikalaichev** [comment]
Faced with the same issue.

Thank you in advance)

**Comment by va1shn9v** [comment]
Updated, demo.py with tiling options, kindly let me know if this helps
