### ISSUE TITLE
Question about Possible Mismatch between Feature Size and Prompt Size

### ISSUE THREAD

**Issue by csguoh** [va1shn9v/PromptIR#21]
Hi, 
Thanks for this incredible work! I have a question about the possible different feature size between pre-defined prompts and image features.  It seems that the spatial size of prompts are pre-defined (such as 64x64 ) and fixed, so if the feature size of one testing image does not match this pre-defined size, hot to handle this?
Thx.

**Comment by va1shn9v** [comment]
Hi, thanks for your interest in our work, we just upsample the prompt Tensors, to match the size/resolution of the features.

**Comment by csguoh** [comment]
Got it! Thanks for your reply :D
