### ISSUE TITLE
A question about the prompt in the paper.

### ISSUE THREAD

**Issue by shallweiwei** [va1shn9v/PromptIR#24]
A great work!
I'm confused about the prompt-component.It seems to be fixed across tasks.
But I'm starting to think that it should be different between tasks, is there a problem with my understanding, so how does the model differentiate between tasks?

https://github.com/va1shn9v/PromptIR/blob/644e529287035ade5824f816f2caaf81883cbfb8/net/model.py#L221

**Comment by Yaziwel** [comment]
> A great work! I'm confused about the prompt-component.It seems to be fixed across tasks. But I'm starting to think that it should be different between tasks, is there a problem with my understanding, so how does the model differentiate between tasks?
> 
> https://github.com/va1shn9v/PromptIR/blob/644e529287035ade5824f816f2caaf81883cbfb8/net/model.py#L221

The feature maps of inputs from various tasks will predict varying weights to assign to N prompts, thereby generating the final prompt. Throughout this process, prompt generation evolves in response to the input.

**Comment by shallweiwei** [comment]
So the various of prompts are because of the feature maps？It's kind of like a classification task. Is there any possibility of misclassification, such as denoising tasks being classified as deraining tasks?
