### ISSUE TITLE
Issue with Pretrained Model Google Drive Link

### ISSUE THREAD

**Issue by wei086** [va1shn9v/PromptIR#25]
I encountered an issue with the pretrained model's Google Drive link provided in this repository. The link appears to be broken/non-functional, which prevents accessing the pretrained model. Can this be checked and updated? Thank you!
link:https://drive.google.com/file/d/1wkw5QCQyM2msQOpV-PL2uag3QLs8jYFc/view?usp=sharing

**Comment by va1shn9v** [comment]
Hello,

Thanks for your interest in our work. You can get the pretrained checkpoints from the released page: https://github.com/va1shn9v/PromptIR/releases/tag/v1.0
