### ISSUE TITLE
Training Cost (GPU and training time)

### ISSUE THREAD

**Issue by Amazingren** [va1shn9v/PromptIR#3]
Thanks for your impressive work.

I like the prompt-based idea. May I know how many GPUs (also which type) you used and how long it tasks to train the model?

It would help me a lot.

Bests,

**Comment by va1shn9v** [comment]
Hello,

Thanks for taking an interest in our work. We trained the model on 4 V100 GPUs with a batch size of 8 per GPU. It took close 3 and half days to fully train the model.
Hope this helps.

**Comment by Amazingren** [comment]
> Hello,
> 
> Thanks for taking an interest in our work. We trained the model on 4 V100 GPUs with a batch size of 8 per GPU. It took close 3 and half days to fully train the model. Hope this helps.

Got it, Thanks a lot!

**Comment by Aniruth1011** [comment]
Is the v100 , 16GB config or 32 GB Config ?
