### ISSUE TITLE
Request for Restormer Pre-trained Model from Table 10

### ISSUE THREAD

**Issue by CaO1205** [va1shn9v/PromptIR#34]
Hi,
I'm working on a project that's closely related to your awesome PromptIR. Your work has been incredibly helpful to me.
I was wondering if you could share **the pre-trained model of Restormer** that you used in the Table 10. It would be a huge help for my project.
![屏幕截图 2024-07-10 172056](https://github.com/va1shn9v/PromptIR/assets/75190031/ec982224-3b4e-4da8-b07b-bc34cbe58391)
Thanks a lot for your time and help!
Best regards,
Theo

**Comment by va1shn9v** [comment]
Hello, thanks a lot for your interest in our project. I currently do not have those pre-trained weights, but with current codebase it should be possible to train a restormer model on all the tasks
