### ISSUE TITLE
About the performance on Rain100L dataset in single-task setting.

### ISSUE THREAD

**Issue by csguoh** [va1shn9v/PromptIR#8]
Hi, authors. Thanks for your awesome work!
I have a question about the PSNR on Derain task under single-task setting.
In the original [Restormer](https://arxiv.org/abs/2111.09881) paper,  the Table 1 in this paper show the PSNR on Rrain100L is 38.99dB.
However, in the PromptIR paper, the Table 3 show the PSNR of Restormer on Rain100L is 36.74dB.
I have no idea about this. Is there some setting different between the two? Can you give a further explanation?

Thank you!

**Comment by va1shn9v** [comment]
Hello,
Thanks a lot for taking interest in our work.
Restormer paper and PromptIR paper use different datasets for training on deraining task. Restormer uses a combined dataset of around 14000 images, while we use Rain100L, which consists of 200 large images

**Comment by csguoh** [comment]
Thanks for your reply. 
By the way, i have another question that the Prompt technique is usually used for tuning a pre-trained model to adapt to other tasks. But it seems that PromptIR makes all the parameters trainable.  Could the authors give me some insight about this design?

Thanks :D

**Comment by chensming** [comment]
> Thanks for your reply. By the way, i have another question that the Prompt technique is usually used for tuning a pre-trained model to adapt to other tasks. But it seems that PromptIR makes all the parameters trainable. Could the authors give me some insight about this design?
> 
> Thanks :D

Hi, bro, I have the same doubts. Have you figured it out yet?
