### ISSUE TITLE
About the All-in-one performance

### ISSUE THREAD

**Issue by chensming** [va1shn9v/PromptIR#9]
Hi, I am interested in your work. And I reproduce the experiment. And I got the results  as followings:

![image](https://github.com/va1shn9v/PromptIR/assets/45591767/08599adf-a7dd-4e58-bd3e-5d9d2e007094)

The first line is the result I reproduced, the second line is the result in the paper.
I found the task of going to the rain to be much higher than in the thesis, and none of the other tasks lived up to the thesis. Did I set it up wrong somewhere? 
I changed the batch size from 8 to 4 because of the cuda memory.
And I followed [issue 4](https://github.com/va1shn9v/PromptIR/issues/4) to prepare the dataset.

**Comment by va1shn9v** [comment]
Hello,
The results reported in the paper and the model checkpoint released are generated by the model trained for 120 epochs, using a batch size of 8. 
The above results seem to be reported after 50 epochs. Please try to train it longer until 120 epochs. I think the performance on dehazing and denoising would improve with more training.
We had observed that batch size of 8 per GPU i.e a total batch size of 32 provided the best result.

**Comment by chensming** [comment]
> Hello, The results reported in the paper and the model checkpoint released are generated by the model trained for 120 epochs, using a batch size of 8. The above results seem to be reported after 50 epochs. Please try to train it longer until 120 epochs. I think the performance on dehazing and denoising would improve with more training. We had observed that batch size of 8 per GPU i.e a total batch size of 32 provided the best result.

oh, thanks. And I also want to know how to get this visualization.

![image](https://github.com/va1shn9v/PromptIR/assets/45591767/a222f112-bf5a-48c1-9505-e862d4c5f6f2)

**Comment by CrazyBrick** [comment]
> > Hello, The results reported in the paper and the model checkpoint released are generated by the model trained for 120 epochs, using a batch size of 8. The above results seem to be reported after 50 epochs. Please try to train it longer until 120 epochs. I think the performance on dehazing and denoising would improve with more training. We had observed that batch size of 8 per GPU i.e a total batch size of 32 provided the best result.
> 
> oh, thanks. And I also want to know how to get this visualization.
> 
> ![image](https://github.com/va1shn9v/PromptIR/assets/45591767/a222f112-bf5a-48c1-9505-e862d4c5f6f2)
> 
> I wonder which of the three prompt generation modules you used to visualize the code？（Since there are 3 prompt components in the model）
> 

hey bro, do you solve the problem,I am also curious about how this image is visualized

**Comment by atti0127** [comment]
> Hi, I am interested in your work. And I reproduce the experiment. And I got the results as followings:
> 
> ![image](https://github.com/va1shn9v/PromptIR/assets/45591767/08599adf-a7dd-4e58-bd3e-5d9d2e007094)
> 
> The first line is the result I reproduced, the second line is the result in the paper. I found the task of going to the rain to be much higher than in the thesis, and none of the other tasks lived up to the thesis. Did I set it up wrong somewhere? I changed the batch size from 8 to 4 because of the cuda memory. And I followed [issue 4](https://github.com/va1shn9v/PromptIR/issues/4) to prepare the dataset.

Can you share your reproduced result?

**Comment by Amazingren** [comment]
您的来信已经收到，稍后进行回复，谢谢~
